name: Sample Book App Workflow

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-install-deps:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - run: echo "Installing all necessary node dependencies.."
      - name: Install all dependencies
        run: npm install
      - run: echo "Dependency installation successful."
  deploy-dev:
    runs-on: self-hosted
    needs: build-install-deps
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Deployment to DEV environment has started.."
      - name: Install dependencies
        run: npm install
      - name: Cleanup of old running services
        run:  .\\node_modules\\.bin\\pm2 delete \"books-dev\" || exit 0
      - name: Run Service
        run:  .\\node_modules\\.bin\\pm2 start -n \"books-dev\" index.js -- -- 1010

  test-dev:
    runs-on: self-hosted
    needs: deploy-dev
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Installing all necessary node dependencies.."
  deploy-stg:
    runs-on: self-hosted
    needs: test-dev
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Installing all necessary node dependencies.."
  test-stg:
    runs-on: self-hosted
    needs: deploy-stg
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Installing all necessary node dependencies.."
  deploy-prd:
    runs-on: self-hosted
    needs: test-stg
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Installing all necessary node dependencies.."
  test-prd:
    runs-on: self-hosted
    needs: deploy-prd
    steps:
      - uses: actions/checkout@v6
      - name: Print step name
        run: echo "Installing all necessary node dependencies.."